frr defaults traditional
hostname r1
service integrated-vtysh-config
interface eth1
 ip ospf network non-broadcast
exit
router ospf
 ospf router-id 1.1.1.1
 neighbor 10.101.12.3
 network 10.101.1.0/24 area 0
 network 10.101.12.0/24 area 0
 passive-interface eth0
exit
